var GAME_LEVELS = [
  [" x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x",
   " x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x",
   " xxxxxxxvxxxxxxxxxxxxxxxxxxxxvxxxxxxxxxxxvvvxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                ",
   "                  yy yy                                                         ",
   " x              y       y                                              $        ",
   "!x  @  x         y     y                        d                               ",
   "xxxxxxxx          yyyyy                    y    p    y                        xx",
   "       x                                    y       y           o               ",
   "       x   o o                               y     y            o          xx   ",
   "       xxxxxxxxxxxxxxxxx                y               y                       ",
   "                       x!!!!!x           y             y              xxx       ",
   "                       x!!!!!x            y           y          o              ",
   "                       xxxxxxx             yyyyyyyyyyy           xxxx           ",
   "                             x                                                  ",
   "                             x o                         xxxxx             x    ",
   "                             xxxxx                            o                o",
   "                                 x                            x!!!!!!!!!!!!!!!xx",
   "                                 x   x            xxxxxxx     x!!!!!!!!!!!!!!!!x",
   "                                 x!!!x      xx        o x!!!!!xxxxxxxxxxxxxxxxxx",
   "                                 x!!!x                o x!!!!!x                 ",
   "                                 xxxxxxxx!!!!!!!xxxxxxxxxxxxxxx                 ",
   "                                        xxxxxxxxxx                              ",
   "                                                                                "],
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "           vvvvvvv   vvvv         vvvv      v                   v        vvvvv   ",
   "          |                     |                                                ",
   "                                                                                 ",
   "                                                                                 ",
   "                                                                                 ",
   "                                                                                 ",
   "     @                            o        =   x     x      =        x   x d x   ",
   "    xxx         xxxxxxxxxxxxxxxxxxxxxxxx  xxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "    x x                        =  o            x                          oo     ",
   "!!!!x x   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    xxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!x x   =            xxxxxxxxxxxxxxxxxx   |       $                            ",
   "!!!!x x                           o                                     =        ",
   "!!!!x x  x xxxpxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxx      xxxxxxxxxxxxxxxxxxxxxx",
   "!!!!x x!!!!!!x         x!!!!xxx       xxxxxxxxxxxxxx!!!!!!xx                     ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!!xx                     ",
   "xxxxxxxxxxxxxx         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                     "],
   [" x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x",
    " x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x",
    " xxxxxxxvxxxxxxxxxxxxxxxxxxxxvxxxxxxxxxxxvvvxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "                                 |                                      |       ",
    "                                                                                ",
    "                    $                                                           ",
    "!x  @            y     y                        d                               ",
    "xx  xxxx   xx     yyyyy          |          y       y                         xx",
    "     ===                                    y       y           o               ",
    "       x   o o                              y       y           o          xx   ",
    "       xxxxxxxxxxxxxxxxx                          x             p               ",
    "                                                                                ",
    "                                                                        |       ",
    " =                                              x                               ",
    "         o                                                                      ",
    "      y     y    x      xxxxxx              pyyyyyyyyyyyp         xxxx          ",
    "        yyy                     x                                               ",
    "                             x o                         xxxxx             x    ",
    "                             xxxxx                            o                o",
    "!xxx!!!!!!!!!!!!!!!!x!!!!!!!!!!!!=                                              ",
    "                                 x   x            xxxxxxx     x!!!!!!!!!!!!!!!!x",
    "                                 x!!!x      xx        o x!!!!!xxxxxxxxxxxxxxxxxx",
    "                                 x!!!x                o x!!!!!x                 ",
    "                                 xxxxxxxp!!!!!!!pxxxxxxxxxxxxxx                 ",
    "                                        xxxxxxxxxx                              "],
    ["|x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x",
     " x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x",
     " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
     "                                                                                ",
     " $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$",
     "                                                                                ",
     "                                                                                ",
     "                                                                                ",
     "                                                                                ",
     "    d               d  d  d     d d     d ddddddd dddddd  y                     ",
     "     d             d   d  d d   d d d   d d       d     d y                     ",
     "  @   d     d     d    d  d  d  d d  d  d dddddd  dddddd  y                     ",
     "  xxx  d   d d   d     d  d   d d d   d d d       d   d   y                     ",
     "        d d   d d      d  d    d  d    d  d       d    d                        ",
     "         d     d       d  d     d d     d ddddddd d     d y                     ",
     "                                                                                ",
     "                                                                                ",
     "                                                                                ",
     "                                                                                ",
     "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
     "pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp"],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
